pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub
                git 'https://github.com/sindhurv18/quick.git'
            }
        }
        
        stage('Deploy to Minikube') {
            steps {
                // Apply Kubernetes manifests
                dir('jenkins-minikube') {
                    // Apply secret
                    sh 'kubectl apply -f secret.yaml'
                    
                    // Apply deployment
                    sh 'kubectl apply -f deployment.yaml'
                    
                    // Wait for deployment to be ready
                    sh 'kubectl rollout status deployment/portal-deployment'
                }
            }
        }
    }
}
