pipeline {
    agent any
    
    environment {
        NAMESPACE = 'default' // Namespace where you want to deploy your manifests
    }
    
    stages {
        stage('Checkout') {
            steps {
                script {
                    git credentialsId: 'git', url: 'https://github.com/sindhurv18/quick.git', branch: 'master' // Replace with your GitHub repository URL and credentials ID
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Apply Kubernetes manifests to Minikube cluster
                    sh 'kubectl apply -f secret.yaml -f deployment.yaml --namespace=$NAMESPACE'
                }
            }
        }
    }
}
