pipeline {
    agent any
    
    stages {
        stage('Install kubectl') {
            steps {
                script {
                    // Change directory to Jenkins workspace
                    dir("$WORKSPACE") {
                        // Download kubectl into Jenkins workspace
                        sh 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
                        // Make kubectl executable
                        sh 'chmod +x kubectl'
                    }
                }
            }
        }
        
        stage('Checkout') {
            steps {
                script {
                    // Clone the repository containing Kubernetes manifest files
                    git credentialsId: 'git', url: 'https://github.com/sindhurv18/quick.git', branch: 'master'
                }
            }
        }

        stage('Debug') {
            steps {
                script {
                    sh 'ls -l $WORKSPACE'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                script {
                    // Apply Kubernetes manifests to Minikube cluster
                    sh '$WORKSPACE/jenkins-minikube/ kubectl apply -f $WORKSPACE/jenkins-minikube secret.yaml -f $WORKSPACE/jenkins-minikube deployment.yaml --namespace=default'
                }
            }
        }
    }
}
